language: python

before_install:
- openssl aes-256-cbc -K $encrypted_9ad75d8875a0_key -iv $encrypted_9ad75d8875a0_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 400 ~/.ssh/deploy_rsa
- chmod +x push.sh

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r api/app/requirements.txt
# command to run tests
script:
  - pytest


jobs:
  include:
  - stage: Test API
    scipt:
      - pytest tests/Login-Register-Edit.py
  - stage: Push
    if: (NOT type IN (pull_request)) AND (branch = master)
    script:
      - "./push.sh"
