language: python

before_install:
- openssl aes-256-cbc -K $encrypted_9ad75d8875a0_key -iv $encrypted_9ad75d8875a0_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 400 ~/.ssh/deploy_rsa
- chmod +x push.sh

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
  - pip install -r api/app/requirements.txt

jobs:
  include:
  - stage: Test API
    scipt:
      - pytest tests/Login-Register-Edit.py
  - stage: Push
    if: (NOT type IN (pull_request)) AND (branch = master)
    script:
      - "./push.sh"
