version: "3"
services:

  server-api:
    build: api/
    expose:
      - "5000"
    ports:
      - "8090:5000"
    env_file:
      - env/api.env
    depends_on:
      - db
      - mongo
    networks:
      - app-tier
    volumes:
    - ./api/app/:/app
    restart: always


  run_applets:
    build:
      context: api
      dockerfile: Dockerfile-applets
    env_file:
      - env/run_applets.env
    depends_on:
      - db
      - mongo
      - server-api
    networks:
      - app-tier
    restart: always

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    env_file:
      - env/db.env
    networks:
      - app-tier
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data
    restart: always

  client-web:
    image: httpd:2.4
    ports:
      - "8081:80"
    depends_on:
      - server-api
    networks:
      - app-tier
    volumes:
      - ./web/app:/usr/local/apache2/htdocs/
    restart: always

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - app-tier
    env_file:
      - env/mongo.env
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - app-tier
    env_file:
      - env/mongo-express.env

networks:
  app-tier:

volumes: 
  db-data:
  mongo-data: