version: "3"
services:

  api:
    build: api/
    expose:
      - "5000"
    ports:
      - "8090:5000"
    environment:
      FLASK_ENV: "development"
      SERVER_ADDRESS: "http://jarvis-app.fr:8090"
      JWT_SECRET_KEY: "y8pugPjzqjUQCF6Y2NdOk5PwKbZ7SsJi"
      OAUTH_CLIENT_ID_GOOGLE: "898500682257-2ciaf88aim1ftr8d4b7tv0hdf88jqkj3.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "DOLyJWPJFJyJxps_0jvEiJhM"
      SPOTIFY_CLIENT_SECRET: "4769232bcb954ca1845229d6c82defe5"
      PUSHBULLET_CLIENT_SECRET: "dTegFPrMmLKg63WY5BG26RDTR2V7JK1H"
      GITHUB_CLIENT_SECRET: "7eb681a358701129aa352d6bb83a8effb2c9334e"
      MASTODON_CLIENT_SECRET: "Q678hXO9Y2XBQbbFgZrDUMKaN7BUuqmRpfqsnj28WRA"
      OUTLOOK_CLIENT_SECRET: "QI-[CLhJ9?xE1=Z6Lykm80tEX.ex3M-Z"
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "example"
    depends_on:
      - db
      - mongo
    networks:
      - app-tier
    volumes:
    - ./api/app/:/app
    restart: always


  run_applets:
    build:
      context: api
      dockerfile: Dockerfile-applets
    environment:
      OAUTH_CLIENT_ID_GOOGLE: "898500682257-2ciaf88aim1ftr8d4b7tv0hdf88jqkj3.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "DOLyJWPJFJyJxps_0jvEiJhM"
      SPOTIFY_CLIENT_SECRET: "4769232bcb954ca1845229d6c82defe5"
      PUSHBULLET_CLIENT_SECRET: "dTegFPrMmLKg63WY5BG26RDTR2V7JK1H"
      GITHUB_CLIENT_SECRET: "7eb681a358701129aa352d6bb83a8effb2c9334e"
      MASTODON_CLIENT_SECRET: "SaRFN58CFuMB9utvytUFRQHaQnKmVZtY34OKvucEKnU"
      OUTLOOK_CLIENT_SECRET: "QI-[CLhJ9?xE1=Z6Lykm80tEX.ex3M-Z"
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "example"
    depends_on:
      - db
      - mongo
      - api
    networks:
      - app-tier
    restart: always

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    networks:
      - app-tier
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data
    restart: always

  web:
    image: httpd:2.4
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - app-tier
    volumes:
      - ./web/app:/usr/local/apache2/htdocs/
    restart: always

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - app-tier
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - app-tier
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  app-tier:

volumes: 
  db-data:
  mongo-data: